### ISSUE TITLE
Add temporary code to prevent display of a11y strings in Rosetta

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#195] opened 2018-07-05 21:16 UTC
Some work is underway to move a11y strings into the strings files, see #193 (the are currently in a completely separate file).  Eventually, we will need to enhance rosetta to support translation of these strings, but for the short term we should add code that avoids displaying them to the translators.  As of this writing, there are no published sims what have a11y strings in their string files, but we don't want to get caught flat footed when one is published.

**Comment by pixelzoom** [comment] 2019-03-26 00:26
Related to https://github.com/phetsims/rosetta/issues/193.

**Comment by pixelzoom** [comment] 2019-03-26 00:27
As noted in

> Marking this for dev meeting discussion.   I was OK with deferring this until it started showing up in sims that I'm responsible for. 
> 
> We now have 19 `*A11yStrings` files, which we will eventually need to move to the `*strings_en.json` files.  And we're currently getting none of the benefits of having these strings in the .json files.  For example, in https://github.com/phetsims/molarity/issues/64, I discovered at least one string in `MolarityA11yStrings` that is unused in the sim.  That's something that would have been detected if a11y strings were in the .json file.
> 
> So how about if we define the metadata that identifies a string as a11y, and (for now) hide all strings with that flag in Rosetta.

**Comment by pixelzoom** [comment] 2019-04-03 22:46
@jbphet Assuming that metadata identifies which strings are specific to a11y, what is your estimate for modifying Rosetta so that it (for now) ignores those strings?

**Comment by zepumph** [comment] 2019-10-07 23:14
Though this is much older, this has become the duplicate of https://github.com/phetsims/rosetta/issues/214, which is more inline with the more up-to-date path of ignoring a11y strings.

>what is your estimate for modifying Rosetta so that it (for now) ignores those strings?

After discussing with @jbphet this morning, we don't think that it will be difficult/time-intensive to ignore a11y strings now that the nested string objects has been implemented. Please see that other issue for details and if you have other questions.

**Closed by zepumph** 2019-10-07 23:14 UTC
Labels: dev:a11y
