### ISSUE TITLE
Pushes failing

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/rosetta#145] opened 2017-01-31 01:18 UTC
At least 18 failure messages in the last week, for example:
```
Error: Repo updateContents error

Error: Repo updateContents error. Error committing to file joist/joist-strings_sv.json

[]
```
or
```
Error: Repo updateContents error

Error: Repo updateContents error. Error committing to file joist/joist-strings_bg.json

[{"stringKey":"menuItem.getUpdate","stringValue":"Провери\\nза обновления"},{"stringKey":"updates.checking","stringValue":"Проверява\\nза обновления"},{"stringKey":"credits.graphicArts","stringValue":"Графични\\nдизайнери: {0}"},{"stringKey":"credits.leadDesign","stringValue":"Водещи\\nдизайнери: {0}"},{"stringKey":"credits.qualityAssurance","stringValue":"\r\nКачествен\\nконтрол: {0}"},{"stringKey":"credits.softwareDevelopment","stringValue":"Разработил\\nсофтуера: {0}"},{"stringKey":"termsPrivacyAndLicensing","stringValue":"Условия,\r\n\\nповерителност и лиценз"},{"stringKey":"updates.newVersionAvailable","stringValue":"Има нова\\nверсия: {0}"},{"stringKey":"thirdParty.credits.link","stringValue":"\r\nИзползвани\\nавторски права"},{"stringKey":"updates.offline","stringValue":"\r\nНе може да\\nсе обнови"},{"stringKey":"updates.yourCurrentVersion","stringValue":"Настоящата версия: {0}"}]
```

We should investigate. Additionally, since I'm less involved, how can I not get these emails?

**Comment by jbphet** [comment] 2017-01-31 16:19
This is a duplicate of https://github.com/phetsims/rosetta/issues/105, check there for more information.  I'll remove @jonathanolson from the email distribution list today.  Closing.

**Closed by jbphet** 2017-01-31 16:19 UTC
Labels: type:bug
