### ISSUE TITLE
Add ability to run all server tests at once

### ISSUE THREAD

**Issue by zepumph** [phetsims/rosetta#191] opened 2018-05-18 00:44 UTC
Currently I see the route `/runTest/:testID?` but no way to run all of the unit tests in the `ServerTests.js` module. It would be nice to have a way to just iterate through all of these and run them all. This also seems like a high priority to me, because I want to have a good sense of how things are working/passing tests before I go messing with stuff.

**Comment by zepumph** [comment] 2018-05-18 00:49
@jbphet  how does that look to you?

**Comment by jbphet** [comment] 2018-05-18 21:44
Sounds like a good idea.  I looked over the implementation and have a couple of comments:

+ I think it would be better to use consistent terminology for 'execute' and 'run', so I'd rather see the exported method names be 'runTest' and 'runAllTests' or 'executeTest' and 'executeAllTests'.
+ I think it would be better if the test summary had properties 'passedCount' and 'failedCount', since 'passed' and 'failed' seem like they could just be booleans.

**Comment by zepumph** [comment] 2018-10-24 23:31
@mbarlow12 I'm not working on rosetta anymore. Would you like to take this on?

**Comment by jbphet** [comment] 2019-09-30 19:02
@mbarlow12 is no longer working on the translation utility.  This seems like something that would be worthwhile someday, but the test facility isn't being used much, and this particular feature seems like a low priority to me.  I'm going to mark this issue as deferred for now.  We can get back to it - or come up with a better way to regression test Rosetta - if there ever comes a time when we are focused on doing more work on it.

**Comment by liam-mulhall** [comment] 2021-02-17 19:14
Someone actually added this, but I removed all of these old tests today. The plan is to use QUnit and integrate Rosetta with Aqua. Closing.

**Closed by liam-mulhall** 2021-02-17 19:14 UTC
Labels: dev:enhancement, priority:5-deferred
