### ISSUE TITLE
Testing failure in RTL locale

### ISSUE THREAD

**Issue by arouinfar** [phetsims/rosetta#136] opened 2016-09-06 17:28 UTC
When testing the translation of Charges and Fields in the fa locale, many odd characters appeared. (The translation submitted normally, however, and is fine.)
<img width="1153" alt="screen shot 2016-09-06 at 11 14 53 am" src="https://cloud.githubusercontent.com/assets/8419308/18283609/4b93ad26-7423-11e6-8117-6de654b82520.png">

Testing the fa translation before entering sim-specific strings (only common strings translated) still resulted in some odd characters in the About menu.
<img width="400" alt="screen shot 2016-09-06 at 11 15 13 am" src="https://cloud.githubusercontent.com/assets/8419308/18283610/4b9474f4-7423-11e6-8741-cd84a1fba17d.png">

However, a sim with fewer strings in general appears to test correctly in fa.
<img width="1046" alt="screen shot 2016-09-06 at 11 17 01 am" src="https://cloud.githubusercontent.com/assets/8419308/18283650/791e9e72-7423-11e6-9fae-8dfc68d379e2.png">

I also tested a dummy translation of Charges and Fields with an LTR language (Dutch) and input a few random strings, and the sim appeared normal.

**Comment by phet-steele** [comment] 2016-09-06 17:35
This finding is consistent with both Charges and Fields & Rutherford Scattering (the two new sims since the server switch). This, I believe, is why Friction in the above comment is fine; Friction was published prior to the server switch.

**Comment by arouinfar** [comment] 2016-09-27 01:51
We encountered the same testing failure in Atomic Interactions, which supports @phet-steele's server switch theory.

**Comment by jbphet** [comment] 2016-11-18 19:57
I ran a test where I removed all but a handful of the Persian (locale=fa) strings, and the problem still shows up, so I don't think that this is related to the long URI issue.  I also tested this with another RTL language - Hebrew - and the problem shows up there for newer sims too.

It doesn't make any sense to me that the switch to a new server would cause this, so I'm assigning to @phet-steele to elaborate.  If it's just the timing, then I think it may be coincidental.  What **does** make sense to me is that something changed about the string plugin or the way that query parameters are processed that messed this up.  We recently made a major change to this with the migration to `QueryStringMachine`, so that may be involved.  So, @phet-steele, if you don't have a lot of insights, please assign this to @jonathanolson once you've responded and he can look into it.  He understands the embedding marks for RTL as well as any of us and has a fair amount of experience with the strings plugin (I just happened to talk with @ariel-phet as I was writing this up, and that's who he suggested take a look at it).

Also mentioning @samreid and @pixelzoom in case they have any immediate insights.

**Comment by pixelzoom** [comment] 2016-11-18 20:04
I see no indication that this issue was fixed, and you say "the problem still shows up".   So I don't understand why you're surprised that this issue is still occurring.  

As another data point... @phet-steele's most recent comment is Sept-9, conversion to QueryStringMachine started on Nov-13.

**Comment by jbphet** [comment] 2016-11-18 20:31
@pixelzoom said:

> I see no indication that this issue was fixed, and you say "the problem still shows up". So I don't understand why you're surprised that this issue is still occurring.

I think there's a bit of a misunderstanding here.  I'm not at all surprised that it isn't fixed, that's not what I was saying.  When I said, "the problem still shows up" I meant that it shows up when very short URI's are used, ergo, it's probably not related to the issue that @arouinfar referenced above.

The info about `QueryStringMachine` is good to know, and likely rules that out as the cause of the problem.

**Comment by pixelzoom** [comment] 2016-11-18 20:36
Got it, thanks for clarification.

**Comment by jonathanolson** [comment] 2016-11-18 21:33
In https://github.com/phetsims/rosetta/issues/115 the double-decoding of the strings query parameter was fixed (changed to a single decoding), however the RTL push and pop remained double-encoded on the rosetta side:
```js
translation = '%E2%80%AB' + translation + '%E2%80%AC';
// ...
var encodedStrings = encodeURIComponent( JSON.stringify( stringsToReplace ) );
```
so basically, ```encodeURIComponent( '\u202b' ) === '%E2%80%AB'```, and so the result had to be decoded twice.

In newer sims, the double-encoding meant that the strings object looks like this:
![friction-translation](https://cloud.githubusercontent.com/assets/480878/20447391/c53b8f2a-ad9b-11e6-933d-d611e5b9c449.PNG)

My fix above changes this to just a single-encoding (matching the newer sims), but this MAY fail on sims that were published before https://github.com/phetsims/rosetta/issues/115 was fixed, as that previous sim-side commit changed the required rosetta behavior.

@jbphet, can you review my change? And we'll presumably need to check to see if any sims don't contain https://github.com/phetsims/rosetta/issues/115's fix.

**Comment by jonathanolson** [comment] 2016-11-18 21:44
It looks like some sims are out WITH the fix from https://github.com/phetsims/rosetta/issues/115 but some aren't (acid-base-solutions was a first example).

Presumably for this behavior, we'd want to run a maintenance release.

@ariel-phet, is this worth a maintenance release to fix (could do at the same time as the maintenance release for Yotta's tracking)? It only affects the ?strings query parameter, so won't affect normal sim operation, but WILL affect the "Test" button for Rosetta, or anywhere else the ?strings query parameter is used.

**Comment by phet-steele** [comment] 2016-11-18 22:39
>It doesn't make any sense to me that the switch to a new server would cause this, so I'm assigning to @phet-steele to elaborate.

I had JO take care of it 😄 

Sims that will need to have a maintenance release (they were relying on double encoding):

- [ ] Acid Base Solutions
- [ ] Arithmetic
- [ ] Balancing Act
- [ ] Balancing Chemical Equations
- [ ] Balloons and Static Electricity
- [ ] Build an Atom
- [ ] Color Vision
- [ ] Energy Skate Park: Basics
- [ ] Faraday's Law
- [ ] Fraction Matcher
- [ ] Graphing Lines
- [ ] Gravity Force Lab
- [ ] Hooke's Law
- [ ] John Travoltage
- [ ] Least Squares Regression
- [ ] Molarity
- [ ] Molecule Shapes
- [ ] Molecule Shapes: Basics
- [ ] Molecules and Light
- [ ] Ohm's Law
- [ ] pH Scale
- [ ] pH Scale: Basics
- [ ] Reactants, Products and Leftovers
- [ ] Resistance in a Wire
- [ ] Trig Tour
- [ ] Wave on a String

**Comment by ariel-phet** [comment] 2016-11-22 01:52
@jonathanolson if we need to do a maintenance release for Yotta tracking anyhow, yes, it would be ideal to roll this fix in with that release.

It does not look as if @jbphet has reviewed this change yet, so perhaps talk with him the week of 11/28/2016?

**Comment by jbphet** [comment] 2016-11-29 23:40
The commit looks good, though since it adds the explicit LTR embedding marks it may actually exacerbate the issue with long URLs (https://github.com/phetsims/rosetta/issues/139), but let's not worry about that for now.

I'd like to test this before going live on phet-server, and will try to do so within the next couple of days.

**Comment by jbphet** [comment] 2016-12-01 00:53
I was about to try testing this on the dev server, and thought I'd remind myself of how to duplicate the issue, but as of this moment I can't duplicate it on the live version of Rosetta.  I can see that the change that @jonathanolson made has been pulled to phet-server, but I don't see any record of a restart in the log.  However, the logs only go back to Nov 23, so perhaps it was restarted with the change before then (the change was submitted on Nov 18th).  Weird.

It's odd that *none* of the sims exhibit the issue.  We had expected that putting this fix in place would make the new sims work correctly but the old sims have problems.  There are a couple of mysteries here.

Assigning to @mattpen to see if he thinks Rosetta may have been restarted in the last 12 days.

Assigning to @jonathanolson to take a look and see if he understands why all sims now seem to be working.

**Comment by jonathanolson** [comment] 2016-12-01 06:41
> Assigning to @mattpen to see if he thinks Rosetta may have been restarted in the last 12 days.

There was a recent automated commit, maybe this triggered a rosetta restart? (https://github.com/phetsims/rosetta/commit/7f6990db5c97bb0b7ce125ffe554ff5e12546b5f)

The rosetta repo on phet-server definitely pulled my fix, and was presumably restarted (since the fix is being applied live!)

> Assigning to @jonathanolson to take a look and see if he understands why all sims now seem to be working.

The sims without the maintenance release seem to be working since they mostly don't involve symbols that will get handled by decodeURIComponent. Say I wanted ```%7B``` in a string in a non-patched sim:
![screen shot 2016-11-30 at 11 33 51 pm](https://cloud.githubusercontent.com/assets/480878/20784118/7d86e198-b755-11e6-9a4c-7b359082d676.png)
That won't work, since it IS a pattern that the double-decode will convert:
![screen shot 2016-11-30 at 11 34 14 pm](https://cloud.githubusercontent.com/assets/480878/20784128/93f2b2c2-b755-11e6-8e69-6bded9455ce1.png)

So, it's _less_ broken, and probably mainly relevant for strings with %'s in them. Maybe that lowers the pressure for a maintenance release?

Sims that WOULD be currently broken (beers-law-lab, bending-light) have the more recent SHA, and wave-on-a-string's patternValueUnitPercentage isn't in the deployed sim.

**Comment by jbphet** [comment] 2016-12-03 00:38
I just did a `ps aux | grep rosetta` on phet-server and, if I'm interpreting the output correctly, the rosetta process hasn't been restarted since Oct 24 2016.  I also looked through the logs and saw no evidence of a restart over the last month.  So, are we sure that the new code is really being run?

**Comment by jbphet** [comment] 2016-12-05 17:57
@jonathanolson and I looked at this today during core hours, and it definitely appears that rosetta is running the fixed code, but has not been restarted.  This is a bit mysterious, and would seem to imply that it is dynamically loading updated code.  If true, we need to be very careful about what we commit to rosetta.  Indeed, we should probably do all future development on branches until we figure out what is going on with this.

**Comment by jbphet** [comment] 2016-12-05 17:59
Since the issue of RTL testing is mostly resolved (details explained above) and the only sims with special characters have the necessary update, @jonathanolson and I are making the recommendation that we *not* do a maintenance release and that we just let this change get incorporated as sims are deployed from master.  Assigning to @ariel-phet to make sure that he is okay with this and, if so, he can close.

**Comment by jonathanolson** [comment] 2016-12-06 18:56
@ariel-phet, if this is still desired in the maintenance release, please let me know in the next few hours if possible.

**Comment by ariel-phet** [comment] 2016-12-06 18:57
Not desired considering your recommendation. Closing

**Closed by ariel-phet** 2016-12-06 18:57 UTC
Labels: type:bug
