### ISSUE TITLE
Validation differences for normal/HTML text

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/rosetta#156] opened 2017-06-22 20:26 UTC
RichText supports an HTML subset that we'll presumably want to validate in the future. We'll also want to tag strings with how they are used in the sim, so that rosetta can know whether it's meant for RichText, Text, MultiLineText, etc.

Marked as deferred, presumably handle when translating of iOS/Android apps.

**Comment by liammulh** [comment] 2023-05-17 23:10
Closing this issue as a duplicate of https://github.com/phetsims/rosetta/issues/333. Keeping #333 because it has more info.

**Closed by liammulh** 2023-05-17 23:10 UTC
Labels: priority:5-deferred
