### ISSUE TITLE
User request: comma as decimal separator

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#252] opened 2021-01-05 16:54 UTC
> I am translating animations into norwegian.I have tranlated https://phet.colorado.edu/nb/simulation/ph-scale-basics, and I wonder if it is possible to change the decimal point from «dot» to «comma»

Here's a relevant email thread from @ariel-phet. At the time, this hadn't been a common request.

> I just dug through phethelp and there were only a couple relevant emails. One from 2011 from a Spanish translator and another in 2014 from a user that was expecting commas instead of points. 
> 
> So, definitely not a common request.
> 
> > On Nov 18, 2016, at 12:11 PM, Ariel J Paul <ariel.paul@Colorado.EDU> wrote:
> > 
> > Hey Oliver,
> > 
> > Have any international users ever complained that we display decimal points as decimal points not as commas? For instance in sims like bending light (index of refraction 1.XX or such)?
> > 
> > Ariel

Assigning to @ariel-phet for now, I think this is the relevant repo?

**Comment by muedli** [comment] 2021-01-05 18:20
@oliver-phet and @ariel-phet, I don't think we have an easy way of doing this right now, but we could probably implement something. I don't think it would be very high priority though.

**Comment by ariel-phet** [comment] 2021-01-05 20:19
@muedli I think it would be worth putting on your radar, but agreed, not a high priority

**Comment by jbphet** [comment] 2021-01-13 17:46
There is some history to the idea of supporting i18n of decimal separators.  The bottom line is that we've wanted to do it for a while, but it has never become a high enough priority that we actually allocate the time to do it.  See https://github.com/phetsims/dot/issues/68.

**Comment by samreid** [comment] 2021-01-25 17:16
In my opinion, PhET should look "at home" in other languages, and the only reason to delay or forego this issue is if it is prohibitively expensive.

**Comment by liam-mulhall** [comment] 2022-07-09 04:50
This is a duplicate of https://github.com/phetsims/rosetta/issues/263. Closing in favor of the older issue.

**Closed by liam-mulhall** 2022-07-09 04:50 UTC
Labels: priority:4-low, type:i18n, type:user-feedback
