### ISSUE TITLE
User reported issue: test url too long

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#139] opened 2016-09-29 17:51 UTC
> When I tried to Test my translation at one stage I got this message:
> Request-URI Too Long
> The requested URL's length exceeds the capacity limit for this server.
> I have copied the URL from the browser window:

`https://phet.colorado.edu/sims/html/least-squares-regression/latest/least-squares-regression_en.html?strings=%7B%22LEAST_SQUARES_REGRESSION%2Fcustom.graphTitle%22%3A%22Egy%C3%A9ni%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusLatitude.graphTitle%22%3A%22H%C5%91m%C3%A9rs%C3%A9klet%20(%CB%9AC)%C2%A0%E2%80%94%20f%C3%B6ldrajzi%20sz%C3%A9less%C3%A9g%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusLatitude.yAxisTitle%22%3A%22%C3%81tlagos%20janu%C3%A1ri%20h%C5%91m%C3%A9rs%C3%A9klet%20(%CB%9AC)%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusLatitude.xAxisTitle%22%3A%22Sz%C3%A9less%C3%A9gi%20fok%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusLatitude.reference%22%3A%22%C3%81tlagos%20janu%C3%A1ri%20h%C5%91m%C3%A9rs%C3%A9klet%2050%C2%A0amerikai%5Cnv%C3%A1rosban%2C%20a%20f%C3%B6ldrajzi%20sz%C3%A9less%C3%A9g%20f%C3%BCggv%C3%A9ny%C3%A9ben.%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusLongitude.graphTitle%22%3A%22H%C5%91m%C3%A9rs%C3%A9klet%20(%CB%9AC)%C2%A0%E2%80%94%20f%C3%B6ldrajzi%20hossz%C3%BAs%C3%A1g%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusLongitude.yAxisTitle%22%3A%22%C3%81tlagos%20janu%C3%A1ri%20h%C5%91m%C3%A9rs%C3%A9klet%20(%CB%9AC)%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusLongitude.xAxisTitle%22%3A%22Hossz%C3%BAs%C3%A1gi%20fok%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusLongitude.reference%22%3A%22%C3%81tlagos%20janu%C3%A1ri%20h%C5%91m%C3%A9rs%C3%A9klet%2050%C2%A0amerikai%5Cnv%C3%A1rosban%2C%20a%20f%C3%B6ldrajzi%20hossz%C3%BAs%C3%A1g%20f%C3%BCggv%C3%A9ny%C3%A9ben.%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureFahrenheitLatitude.graphTitle%22%3A%22H%C5%91m%C3%A9rs%C3%A9klet%20(%CB%9AF)%C2%A0%E2%80%94%20f%C3%B6ldrajzi%20hossz%C3%BAs%C3%A1g%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureFahrenheitLatitude.yAxisTitle%22%3A%22%C3%81tlagos%20janu%C3%A1ri%20h%C5%91m%C3%A9rs%C3%A9klet%20(%CB%9AF)%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureFahrenheitLatitude.xAxisTitle%22%3A%22Sz%C3%A9less%C3%A9gi%20fok%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureFahrenheitLatitude.reference%22%3A%22%C3%81tlagos%20janu%C3%A1ri%20h%C5%91m%C3%A9rs%C3%A9klet%2050%C2%A0amerikai%5Cnv%C3%A1rosban%2C%20a%20f%C3%B6ldrajzi%20sz%C3%A9less%C3%A9g%20f%C3%BCggv%C3%A9ny%C3%A9ben.%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureFahrenheitLongitude.graphTitle%22%3A%22H%C5%91m%C3%A9rs%C3%A9klet%20(%CB%9AF)%C2%A0%E2%80%94%20f%C3%B6ldrajzi%20hossz%C3%BAs%C3%A1g%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureFahrenheitLongitude.yAxisTitle%22%3A%22%C3%81tlagos%20janu%C3%A1ri%20h%C5%91m%C3%A9rs%C3%A9klet%20(%CB%9AF)%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureFahrenheitLongitude.xAxisTitle%22%3A%22Hossz%C3%BAs%C3%A1gi%20fok%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureFahrenheitLongitude.reference%22%3A%22%C3%81tlagos%20janu%C3%A1ri%20h%C5%91m%C3%A9rs%C3%A9klet%2050%C2%A0amerikai%5Cnv%C3%A1rosban%2C%20a%20f%C3%B6ldrajzi%20hossz%C3%BAs%C3%A1g%20f%C3%BCggv%C3%A9ny%C3%A9ben.%22%2C%22LEAST_SQUARES_REGRESSION%2FspendingSalary.graphTitle%22%3A%22P%C3%A9nzk%C3%B6lt%C3%A9s%20%E2%80%94%20kereset%22%2C%22LEAST_SQUARES_REGRESSION%2FspendingSalary.yAxisTitle%22%3A%22*%C3%81tlagk%C3%B6lt%C3%A9s%20per%20di%C3%A1k%201000%20USD-ben%22%2C%22LEAST_SQUARES_REGRESSION%2FspendingSalary.xAxisTitle%22%3A%22Tan%C3%A1ri%20%C3%A1tlagkereset%201000%20USD-ben%22%2C%22LEAST_SQUARES_REGRESSION%2FspendingSalary.reference%22%3A%22*%C3%81tlagk%C3%B6lt%C3%A9s%20per%20di%C3%A1k%20a%20tan%C3%A1ri%20%C3%A1tlagkeresettel%5Cn%C3%B6sszevetve%2050%20USA%20%C3%A1llamban%201986-ban.%22%2C%22LEAST_SQUARES_REGRESSION%2FwageYear.graphTitle%22%3A%22Minim%C3%A1lb%C3%A9r%20%E2%80%94%20id%C5%91%22%2C%22LEAST_SQUARES_REGRESSION%2FwageYear.yAxisTitle%22%3A%22Infl%C3%A1ci%C3%B3hoz%20igaz%C3%ADtott%20minim%C3%A1lb%C3%A9r%20(USD)%22%2C%22LEAST_SQUARES_REGRESSION%2FwageYear.xAxisTitle%22%3A%221947%20%C3%B3ta%20eltelt%20%C3%A9vek%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusChirp.graphTitle%22%3A%22%C2%A0H%C5%91m%C3%A9rs%C3%A9klet%C2%A0(%CB%9AC)%C2%A0%E2%80%94%20t%C3%BCcs%C3%B6kciripel%C3%A9s%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusChirp.yAxisTitle%22%3A%22%C2%A0H%C5%91m%C3%A9rs%C3%A9klet%C2%A0(%CB%9AC)%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusChirp.xAxisTitle%22%3A%22T%C3%BCcs%C3%B6kciripel%C3%A9sek%20sz%C3%A1ma%2015%20s%20alatt%22%2C%22LEAST_SQUARES_REGRESSION%2FtemperatureCelsiusChirp.reference%22%3A%22T%C3%BCcs%C3%B6kciripel%C3%A9sek%20sz%C3%A1ma%2015%20s%20alatt%20a%20h%C5%91m%C3%A9rs%C3%A9klettel%20%C3%B6sszevetve%22%2C%22LEAST_SQUARES_REGRESSION%2FheightShoe.graphTitle%22%3A%22Magass%C3%A1g%C2%A0%E2%80%94%20cip%C5%91m%C3%A9ret%22%2C%22LEAST_SQUARES_REGRESSION%2FheightShoe.yAxisTitle%22%3A%22Magass%C3%A1g%20(h%C3%BCvelyk)%22%2C%22LEAST_SQUARES_REGRESSION%2FheightShoe.xAxisTitle%22%3A%22Cip%C5%91m%C3%A9ret%20(US)%22%2C%22LEAST_SQUARES_REGRESSION%2FheightShoe.reference%22%3A%22A%20magass%C3%A1g%20becsl%C3%A9se%20a%20cip%C5%91m%C3%A9ret%20alapj%C3%A1n.%22%2C%22LEAST_SQUARES_REGRESSION%2Fsum%22%3A%22%C3%B6sszeg%22%2C%22LEAST_SQUARES_REGRESSION%2FbestFitLine%22%3A%22Legjobban%20illeszt%C5%91%20egyenes%22%2C%22LEAST_SQUARES_REGRESSION%2Fresiduals%22%3A%22Elt%C3%A9r%C3%A9sek%22%2C%22LEAST_SQUARES_REGRESSION%2FsquaredResiduals%22%3A%22N%C3%A9gyzetelt%C3%A9r%C3%A9sek%22%2C%22LEAST_SQUARES_REGRESSION%2FmyLine%22%3A%22Az%20%C3%A9n%20illeszt%C5%91%20egyenesem%22%2C%22LEAST_SQUARES_REGRESSION%2FcorrelationCoefficient%22%3A%22Korrel%C3%A1ci%C3%B3s%5Cnkoefficiens%22%2C%22LEAST_SQUARES_REGRESSION%2FsourcePattern%22%3A%22Forr%C3%A1s%3A%C2%A0%7B0%7D%22%2C%22LEAST_SQUARES_REGRESSION%2Fleast-squares-regression.title%22%3A%22Legkisebb%20n%C3%A9gyzetek%20m%C3%B3dszere%22%2C%22JOIST%2FmenuItem.about%22%3A%22N%C3%A9vjegy%22%2C%22JOIST%2FadaptedFrom%22%3A%22adapt%C3%A1l%C3%A1s%5Cnalapja%22%2C%22JOIST%2FmenuItem.getUpdate%22%3A%22Friss%C3%ADt%C3%A9s%20ellen%C5%91rz%C3%A9se%22%2C%22JOIST%2Fupdates.checking%22%3A%22Friss%C3%ADt%C3%A9s%20keres%C3%A9se...%22%2C%22JOIST%2Fcredits.title%22%3A%22K%C3%B6zrem%C5%B1k%C3%B6d%C5%91k%22%2C%22JOIST%2Fdone%22%3A%22K%C3%A9sz%22%2C%22JOIST%2FmenuItem.fullscreen%22%3A%22Teljes%20k%C3%A9perny%C5%91%22%2C%22JOIST%2Fupdates.getUpdate%22%3A%22Friss%C3%ADt%C3%A9s%20bet%C3%B6lt%C3%A9se%22%2C%22JOIST%2Fcredits.graphicArts%22%3A%22Grafika%3A%C2%A0%7B0%7D%22%2C%22JOIST%2Fcredits.leadDesign%22%3A%22Vezet%C5%91%20tervez%C5%91%3A%C2%A0%7B0%7D%22%2C%22JOIST%2FmenuItem.mailInputEventsLog%22%3A%22Input%20esem%C3%A9nynapl%C3%B3%20emailben%22%2C%22JOIST%2Fupdates.outOfDate%22%3A%22%C3%9Aj%20v%C3%A1ltozat%20%C3%A9rhet%C5%91%20el%22%2C%22JOIST%2Fupdates.noThanks%22%3A%22Nem%20k%C3%A9rem%22%2C%22JOIST%2Foptions.title%22%3A%22Opci%C3%B3k%22%2C%22JOIST%2FmenuItem.options%22%3A%22Opci%C3%B3k...%22%2C%22JOIST%2FmenuItem.outputInputEventsLog%22%3A%22Output-input%20esem%C3%A9nynapl%C3%B3%22%2C%22JOIST%2FmenuItem.phetWebsite%22%3A%22A%20PhET%20oldal%C3%A1ra%22%2C%22JOIST%2Fcredits.qualityAssurance%22%3A%22Min%C5%91s%C3%A9gbiztos%C3%ADt%C3%A1s%3A%C2%A0%7B0%7D%22%2C%22JOIST%2FmenuItem.reportAProblem%22%3A%22Probl%C3%A9mabejelent%C3%A9s%22%2C%22JOIST%2FmenuItem.screenshot%22%3A%22K%C3%A9perny%C5%91felv%C3%A9tel%22%2C%22JOIST%2Ftitle.settings%22%3A%22Be%C3%A1ll%C3%ADt%C3%A1sok%22%2C%22JOIST%2FmenuItem.settings%22%3A%22Be%C3%A1ll%C3%ADt%C3%A1sok...%22%2C%22JOIST%2FshowPointers%22%3A%22Mutat%C3%B3k%20megjelen%C3%ADt%C3%A9se%22%2C%22JOIST%2Fcredits.softwareDevelopment%22%3A%22Szoftverfejleszt%C3%A9s%3A%C2%A0%7B0%7D%22%2C%22JOIST%2FmenuItem.submitInputEventsLog%22%3A%22Input%20esem%C3%A9nynapl%C3%B3%20lead%C3%A1sa%22%2C%22JOIST%2Fcredits.team%22%3A%22Munkat%C3%A1rsak%3A%C2%A0%7B0%7D%22%2C%22JOIST%2FtermsPrivacyAndLicensing%22%3A%22Felt%C3%A9telek%2C%20adatv%C3%A9delem%2C%20enged%C3%A9lyek.%22%2C%22JOIST%2Fcredits.thanks%22%3A%22K%C3%B6sz%C3%B6netnyilv%C3%A1n%C3%ADt%C3%A1s%22%2C%22JOIST%2Fupdates.newVersionAvailable%22%3A%22%C3%9Aj%20v%C3%A1ltozat%20%C3%A9rhet%C5%91%20el%3A%C2%A0%7B0%7D.%22%2C%22JOIST%2FthirdParty.credits.link%22%3A%22Harmadik%20f%C3%A9l%22%2C%22JOIST%2Fupdates.upToDate%22%3A%22Ez%20a%20szimul%C3%A1ci%C3%B3%20naprak%C3%A9sz.%22%2C%22JOIST%2Fcredits.translation%22%3A%22Ford%C3%ADt%C3%A1s%22%2C%22JOIST%2Ftranslation.credits.link%22%3A%22Ford%C3%ADt%C3%B3ink%22%2C%22JOIST%2Fupdates.offline%22%3A%22Nem%20siker%C3%BClt%20a%20friss%C3%ADt%C3%A9s%20keres%C3%A9se.%22%2C%22JOIST%2FversionPattern%22%3A%22Verzi%C3%B3%3A%20%7B0%7D%22%2C%22JOIST%2Fupdates.yourCurrentVersion%22%3A%22Az%20%C3%B6n%20jelenlegi%20verzi%C3%B3ja%3A%C2%A0%7B0%7D.%22%7D`

> It looks pretty long, indeed.
> What shall I do?
> Sándor

**Comment by oliver-phet** [comment] 2016-09-29 17:51
Assigning to @jbphet for now.

**Comment by jbphet** [comment] 2016-09-29 20:04
This is essentially the same issue as https://github.com/phetsims/rosetta/issues/100.  I'll leave them both open as a reminder to test each when I have a fix in place.

**Comment by arouinfar** [comment] 2016-10-03 17:06
@oliver-phet to get around this issue, a translator can temporarily remove a few strings. I would recommend temporarily removing a few common strings that won't show up in the sim itself so that the URL becomes short enough to test. Before submitting the translation, the common strings should be pasted back in. 

This method isn't without risks, however. If a translator forgets to return the deleted common strings before submitting, it will affect all of the sims that have been translated into that locale.

**Comment by jbphet** [comment] 2016-10-11 22:25
I used a utility to count the number of characters in the long URL in the comment above.  It is 8479 characters long.

**Comment by jbphet** [comment] 2016-10-11 22:59
I just tried some experiments to determine the max length URL supported by our server.  It looks like the limit is 8202 characters.

**Comment by jbphet** [comment] 2016-10-11 23:02
I did some research, and it sounds like there is no limit in the HTTP spec for how long a URL can be, but browsers seem to support different limits.  Long term, we probably need to look at an alternative way to support this feature.  In the short term, it may be possible to configure our server to accept longer URLs.

@mattpen - can you take a look at what the current configuration value is and whether it can be increased?  For now, let's try setting the value to 20000.

**Comment by mattpen** [comment] 2016-10-12 02:33
@jbphet - It looks like extending the limit will require editing the Apache source code and recompiling.  

Is it feasible to send this data in a POST request instead of in query parameters?

**Comment by mattpen** [comment] 2016-10-25 15:27
This will be addressed in November with Rosetta v2, unassigning myself for now.

**Comment by jbphet** [comment] 2016-11-15 22:12
We should look at using a POST message to Rosetta and have it process it, replace the strings in the sim's HTML file, and returning that.  I discussed this with @zepumph, and he might have some time to try this out shortly.

**Comment by pixelzoom** [comment] 2018-01-25 17:40
Is this a duplicate of https://github.com/phetsims/rosetta/issues/100?

**Comment by jbphet** [comment] 2018-01-25 22:22
@pixelzoom - yes it is, as noted above in https://github.com/phetsims/rosetta/issues/139#issuecomment-250575777.  I'll go ahead and close that one, but will leave this one open because I want to do a little more testing before closing.

**Comment by jbphet** [comment] 2018-02-20 19:39
The test feature has been changed to use an HTTP Post message, and rosetta receives the request and replaces the strings in the live version of the sim with those in the translator's form.  This appears to work well in almost all cases.  There is one case that I believe still isn't quite right for RTL languages.  The follow screenshots and text describe the problem using the Molecules and Light (MAL) sim.

In the live Persian version of MAL (https://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_fa.html), the control panel looks like this:

![image](https://user-images.githubusercontent.com/3082831/36444368-724effde-1638-11e8-9d3c-6c0689d6a0a2.png)

It should be possible to put the chemical names on the other side of the labels, and I've seen this done in other RTL languages, so I tried it using the "Test" feature (no actual submissions of strings were made).  This is what was changed on the translation page at https://phet.colorado.edu/translate/sim/molecules-and-light/fa:

![image](https://user-images.githubusercontent.com/3082831/36444582-ee9c4754-1638-11e8-8033-c152fa52ed2f.png)

The sim looked like this when the test button was pressed:

![image](https://user-images.githubusercontent.com/3082831/36444636-14981c94-1639-11e8-931c-c3f9dd7f4a0d.png)

This is close - the parentheses and chemical names are in the right place - but the subscripts are in the wrong places.  At first, I thought this was an issue with the code that submits the test request to rosetta, but when I looked at the currently live Arabic version of this sim at https://phet.colorado.edu/sims/html/molecules-and-light/latest/molecules-and-light_ar.html, the control panel also has the issue with subscripts appearing in incorrect places:

![image](https://user-images.githubusercontent.com/3082831/36444936-e91b8e56-1639-11e8-8471-13cb2fa6176c.png)

That starts to make the problem look like it could originate with the RichText node.  @jonathanolson - can you take a look at this and see if you can shed any light on what is going on?  Basically, I need to figure out if we need to do something different with translation strings or if something is up with RichText.

**Comment by jbphet** [comment] 2018-02-21 17:44
@jonathanolson and I discussed this via Zoom, and he recommended embedding specific directives in cases like this where we have text that always should be LTR inside a pattern, see the commit immediately above.

This feature should be fully implemented, assigning to @phet-steele to test drive and, if all looks good, close the issue.  Note that the parens issue in MAL won't be fully resolved until the next time it is published.

**Comment by phet-steele** [comment] 2018-02-21 19:20
This is working well. Tried what the original user was doing (LSR + Hungarian) and there was no problem while "Test"-ing

**Closed by phet-steele** 2018-02-21 19:20 UTC
Labels: priority:2-high
