### ISSUE TITLE
Show translators which sims haven’t been translated into a given locale

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#121] opened 2016-02-18 19:40 UTC
Discussed during developer meeting, we discussed the possibility of improving the UI of the HTML5 translation page so that translators can easily see which simulations haven't been translated into their locale yet.

Simple proposal was to move the locale drop down to the top, then have 2 drop down lists for sims:
1. Sims not yet translated into [locale]
2. Sims already translated into [locale]

This information is (partially) available [here](http://phet.colorado.edu/en/simulations/translated/ar) for every locale but all HTML5 sims (even untranslatable ones) are included.

Down the road, it would be nice to preselect a locale that they generally translate in.

**Comment by ariel-phet** [comment] 2018-02-13 16:26
I think this qualifies more for medium priority, it is a nice enhancement

**Comment by jbphet** [comment] 2019-03-22 21:33
This would indeed be a nice enhancement, but I'm not getting much time to work on translation issues, and when I do that time is going towards higher priority things.  Assigning to @ariel-phet to decide whether this enhancement can be done by @mbarlow12.  If not, we should just leave the issue unassigned until we have some time budgeted to work on things like this.

**Comment by ariel-phet** [comment] 2019-03-25 19:08
@jbphet making unassigned and moving priority to low. 

Translators seem to be pretty good about knowing about new sims (for instance our Japanese translators said they just look for the new sim announcement emails). And translations have been rolling in without much issue. Again, would be a nice enhancement, but things are basically working.

**Comment by liam-mulhall** [comment] 2022-07-09 05:02
This is a duplicate of the main feature being added to Rosetta 2.0. See https://github.com/phetsims/rosetta/issues/284 Closing.

**Closed by liam-mulhall** 2022-07-09 05:02 UTC
Labels: priority:4-low, type:i18n
