### ISSUE TITLE
Swahili translation submitted as Abkhazian

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#324] opened 2022-12-13 22:07 UTC
There is a locale `ab`, which maps to Abkhazian, for which we had never gotten a translation until quite recently.  @liammulh and I often use this locale for testing because it was never used by real translators, and because it's the first one in alphabetical order, which makes it easy to test with.  Surprisingly, we received a translation for this locale recently, but it looks like it was probably a mistake.  I submitted some of the strings to Google Translate to check it out, and it appears that it is actually in Swahili.  You can see the strings file at https://github.com/phetsims/babel/blob/master/beers-law-lab/beers-law-lab-strings_ab.json.

@solaolateju and @RVieyra - I talked with @oliver-phet and verified that the individual who submitted this was from the translator network.  Can you please ask them to re-submit the translation for the appropriate language?  I might be able to move it manually on this end, but I think it would be better for them to be aware of the error.  They probably forgot to select Swahili and just submitted on the default `ab` locale.

**Comment by solaolateju** [comment] 2022-12-14 13:57
Hi @jbphet, 
I agree, it must be an error. We don't have a translator for Abkhazian. 
Do you know the name or email of the translator?

**Comment by jbphet** [comment] 2022-12-14 18:16
@oliver-phet - Can you please provide @solaolateju with the name and email for the translator?

**Comment by oliver-phet** [comment] 2022-12-14 18:20
@solaolateju you can normally get the translator's email on the [translation credit page](https://phet.colorado.edu/en/for-translators/translation-credits/by-locale), but it seems that page might be delayed.
User is bayashaban@gmail.com

**Comment by solaolateju** [comment] 2022-12-14 19:46
Copy. I will have an update tomorrow.

**Comment by solaolateju** [comment] 2022-12-16 10:36
Hi @jbphet 
I haven't heard back from [bayashaban@gmail.com](mailto:bayashaban@gmail.com).  
I found that he is from Tanzania, whose official language is Kiswahili. 
You were right about the translation being done in error. 
I would advise clear the error and retain for the tests.
I will inform him of the error once I am able to connect with him.

**Comment by jbphet** [comment] 2022-12-16 17:58
@solaolateju - I can remove the errant translation, but I have a question first:  We don't have Kiswahili as an available language in the translation utility because it's not in the [ISO 639-1 standard](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).  We have Swahili, but there is already a translation of Beer's Law Lab for that language.  Should I move the translation in question to a different language or just delete it entirely?

**Comment by solaolateju** [comment] 2022-12-16 18:25
@jbphet Apologies, I was mixing up the names. Swahili is the English word while the speakers refer to it as Kiswahili.
Yes, it is ok to delete.

**Comment by solaolateju** [comment] 2022-12-21 04:29
@jbphet [bayashaban@gmail.com](mailto:bayashaban@gmail.com) today confirmed it was a mistake. With Beers Law already translated into Swahili, no additional action is required.

**Comment by jbphet** [comment] 2022-12-21 20:20
Reopening - we still have some follow up to do.

**Comment by jbphet** [comment] 2022-12-21 20:37
I've now deleted the translation files.

@mattpen - There are Abkhazian translations (locale = ab) for Beer's Law Lab and Concentration that are actually Swahili (details above).  See the links below.  These should be removed from the website.

- https://phet.colorado.edu/sims/html/beers-law-lab/latest/beers-law-lab_ab.html
- https://phet.colorado.edu/sims/html/concentration/latest/concentration_ab.html
-

**Comment by mattpen** [comment] 2022-12-22 18:33
These were deleted from the file system and database.

@jonathanolson does anything need to happen here for yotta?

**Comment by jonathanolson** [comment] 2022-12-22 21:10
Yotta might error out, I can add the IDs to its list to ignore. Since I know what happened, I'll take care of that when it happens! Thanks.

**Comment by mattpen** [comment] 2022-12-23 01:00
OK with me to close, website side work is complete.

**Comment by liammulh** [comment] 2022-12-23 07:40
I deleted a comment earlier that had personal info.

Sola was replying to say:

> [Translator] today confirmed it was a mistake. With Beers Law already translated into Swahili, no additional action is required.

**Comment by liammulh** [comment] 2023-02-20 23:52
@jonathanolson, can we close this?

**Comment by jonathanolson** [comment] 2023-02-22 04:49
I handled the yotta bits. Closing.

**Closed by jonathanolson** 2023-02-22 04:49 UTC
