### ISSUE TITLE
Request-URI Too Large Error on Testing RTL Locale

### ISSUE THREAD

**Issue by arouinfar** [phetsims/rosetta#100] opened 2015-11-02 21:41 UTC
My husband is a native Persian speaker and has been made the trusted translator for the fa locale. After translating most of the strings in Hooke's Law (a few Common Strings are temporarily untranslated), he attempted to preview the translation using "Test" and encountered the following error in both the latest Chrome & Firefox.

![image](https://cloud.githubusercontent.com/assets/8419308/10894804/db60abb0-816d-11e5-825b-de454db2c3de.png)

I haven't been able to find any relevant documentation in the User Guide on Drive or other related issues within Rosetta, so I apologize if this is a duplicate.

Here's a screenshot with all of the strings:
![image](https://cloud.githubusercontent.com/assets/8419308/10894751/afa6af60-816d-11e5-98c7-b0c934c56040.png)
![image](https://cloud.githubusercontent.com/assets/8419308/10894779/c6509992-816d-11e5-88cf-2f2944f0b28d.png)

**Comment by ariel-phet** [comment] 2015-11-02 21:44
@aaronsamuel137 I know IE had some URL limitation, but I was not aware of such on FF or Chrome. Might also be a question for @jonathanolson or Tuesday dev meeting

**Comment by arouinfar** [comment] 2015-11-02 21:47
We observed the issue on OSX 10.9.5 and 10.10.5, but haven't tried a Windows machine.

**Comment by aaronsamuel137** [comment] 2015-11-03 01:32
It's not a browser issue, but an issue with apache's length limits. This could probably be changed but many some people warn against it. Here's a link to a stackoverflow where this issue is discussed: http://stackoverflow.com/questions/2586339/how-to-increase-apache-2-uri-length-limit

Probably a good topic to discuss with @jonathanolson and the other developers.

**Comment by arouinfar** [comment] 2015-11-03 19:33
If I remove two strings (adaptedFrom & menuItem.getUpdate, for example) Test no longer fails. This is an easy enough workaround for testing, but I don't know if there will be problems when it comes time to submit the translation.

**Comment by aaronsamuel137** [comment] 2015-11-03 19:40
The submission process will work fine since it doesn't rely on any long URLs. It's probably just barely going over the apache limit for this sim and locale.

**Comment by ariel-phet** [comment] 2015-11-06 19:17
Assigning this to @jonathanolson since it seems like most in his wheelhouse

**Comment by jonathanolson** [comment] 2015-11-09 18:28
A few alternatives to discuss:
1. Pass string data through iframe messages. Requires we don't run sim code before getting the strings, so we would need to do some architectural changes to built sims (scripts => strings that get created as scripts when sim is ready to launch, query parameter that delays launching of sim until iframe message, etc.)
2. Use a POST request to the server (strings not in URL), and have it rewrite the HTML response to embed the string information in the response.
3. Support dynamically changing strings in a sim. This is the best long-term, but is incompatible with most/all of current sims.
4. Rebuild sim HTML on server-side, either patching (like option 2), or with chipper.

**Comment by pixelzoom** [comment] 2015-11-10 00:49
Worth noting is that hookes-law has a relatively small number of strings (29).

**Comment by samreid** [comment] 2015-11-10 19:07
One possibility for the iframe idea:

1. the parent frame sets a global
2. the sim is launched with a query parameter like ?iframe-i18n-mode
3. the sim string plugins checks for the existence of globals in the parent frame

**Comment by samreid** [comment] 2015-11-10 19:08
@jbphet proposed short term solution: increase the URL length limit for apache and advise translators to avoid IE for now.

**Comment by samreid** [comment] 2015-11-10 19:12
@aaronsamuel137 will look into configuring apache to help out here.

**Comment by aaronsamuel137** [comment] 2015-11-12 22:08
I've worked with OIT to reconfigure apache, but haven't tested yet. It looks like this Persian translation was never deployed, so I don't have an easy way to test.

Can you ask your husband to try again @arouinfar?

**Comment by arouinfar** [comment] 2015-11-12 22:58
@aaronsamuel137, it appears that the testing now works. I want to leave this issue open until the translation has been submitted (hopefully in the next day or so), in case we run into any related problems.

**Comment by arouinfar** [comment] 2015-11-13 07:54
We're no longer experiencing any issues while testing, and the Persian translation of Hooke's Law has been successfully submitted, so I'll go ahead and close this issue. Thanks for increasing the apache limit!

**Comment by arouinfar** [comment] 2016-09-27 01:54
When translating Atomic Interactions into the fa locale, we encountered the same 414 error (in addition to #136). Not sure if it's worth reopening this issue, but I wouldn't be surprised if there are still some combinations of sims/locales that are hitting the character limit.

**Comment by arouinfar** [comment] 2016-09-28 18:29
@aadish suggested this could addressed with a post request. 

Character limits will definitely be an issue when we start allowing translations of scene descriptions for accessibility. After talking to @jbphet I'm reopening this issue.

**Comment by pixelzoom** [comment] 2018-01-25 17:40
Is this a duplicate of https://github.com/phetsims/rosetta/issues/139?

**Comment by jbphet** [comment] 2018-01-25 22:22
A fix has been implemented and tested for this, and there is more information available under #139.  Closing.

**Closed by jbphet** 2018-01-25 22:22 UTC
Labels: chipper:2.0, priority:2-high, type:bug
