### ISSUE TITLE
implementation notes needs to be completed

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#75] opened 2015-09-28 17:22 UTC
The implementation-notes.txt file doesn't appear to have been updated during the implementation process.  This should be done to support future maintenance and expansion of the translation utility.

**Comment by aaronsamuel137** [comment] 2015-10-02 15:33
Added some notes here. Anything else you think I should cover?

Assigning to @jbphet for review.

**Comment by jbphet** [comment] 2015-10-06 20:27
I think there should be a bit of a big picture overview of how this works.  The audience that I'm envisioning is someone completely new to the project, since we've had an offer of outside help for working on this.  This document would explain the basic steps, like extracting the strings from the published sim file, pulling them from the various sim and common code repositories, constructing the translation page, allowing the user to save or submit, etc.  So, bottom line, I feel like these notes should be expanded upon.

**Comment by aaronsamuel137** [comment] 2015-10-16 15:43
I've converted this file to md and added the basic steps of how rosetta works. Assigning to @jbphet for review.

**Comment by jbphet** [comment] 2021-02-17 18:23
These notes could probably use an update.  For instance, they seem to reference "octonode", which I believe we no longer used.  @liam-mulhall has been working on rosetta most recently, let's have him take a pass through and update.

**Comment by liam-mulhall** [comment] 2022-06-10 15:10
There will be extensive notes in the new version of Rosetta.

**Comment by liam-mulhall** [comment] 2022-07-09 05:00
This is a duplicate of https://github.com/phetsims/rosetta/issues/280, which is closed.

**Closed by liam-mulhall** 2022-07-09 05:00 UTC
Labels: dev:code-review
