### ISSUE TITLE
Rosetta should strip leading and trailing whitespace added by translators

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#270] opened 2021-09-30 18:27 UTC
In https://github.com/phetsims/chipper/issues/619 it was noted that there are some problems with whitespace in our strings.  We're going to take several steps to deal with this, but one should be to add code to Rosetta to strip out leading and trailing whitespace that is added by a translator when submitting or testing strings.

As part of this effort, we should decide whether to fix existing translations.

**Comment by liam-mulhall** [comment] 2021-09-30 18:28
Noted. Thanks, @jbphet.

**Comment by liam-mulhall** [comment] 2022-07-09 04:45
This is a duplicate of https://github.com/phetsims/rosetta/issues/163. Closing in favor of the older issue.

**Closed by liam-mulhall** 2022-07-09 04:45 UTC
Labels: rosetta:2.0
