### ISSUE TITLE
Not responding incident

### ISSUE THREAD

**Issue by mattpen** [phetsims/rosetta#188] opened 2018-04-26 16:33 UTC
This morning during status rosetta was having some problems.  Web requests for https://phet.colorado.edu/translate were returning Proxy or 503 errors from varnish, indicating timeouts in the request to rosetta.  Steele was able to get in, but Diana, @zepumph, and myself were not.  I noticed the following error in the log several times:

```
Apr 26 10:13:16 phet-server.int.colorado.edu rosetta[65482]: get request received, url = /translate/
Apr 26 10:13:16 phet-server.int.colorado.edu rosetta[65482]: Apr 26 2018 10:13:16 MDT - info: a request for metadata is in progress, waiting on that promise
Apr 26 10:13:16 phet-server.int.colorado.edu rosetta[65482]: Apr 26 2018 10:13:16 MDT - error: unhandled rejection, error.message = Unexpected end of JSON input
```
I checked the status of the metadata and it seemed to be returning requests as expected.  I restarted rosetta and it seems to be working fine for now, assigning to @jbphet to investigate.

**Comment by phet-steele** [comment] 2018-04-26 16:38
> Steele was able to get in

No @mattpen I was not. You can access https://phet.colorado.edu/translate if you are not logged in (which I did), but attempting to log in gives the 503.

**Comment by zepumph** [comment] 2018-04-26 17:56
I can confirm that @phet-steele's UX was the same as mine.

**Comment by jbphet** [comment] 2018-04-27 17:09
I've gone through the log, and I'll summarize what went wrong, then propose a solution, than add more detail to justify my analysis (mostly in case in need to revisit this).

For some reason, rosetta was restarted on Apr 25 at 22:43:09.  As part of its startup process, it attempted to populate the `simData` object by retrieving and interpreting metadata from the website (this is a normal part of startup).  The retrieval failed.  If I were to guess, I'd say maybe all processes, including the website, were being restarted, and the website wasn't ready for the metadata request yet.  There is no good error handling in place for this situation, and the left a non-null rejected promise around as the response to the metadata retrieval request, which caused all subsequent attempts to access the `simData` information to fail.

Restarting rosetta fixed this problem because during the startup it was able to successfully get the metadata from the website.

The most thorough way to handle this situation would be to build in a retry mechanism that would start a timer if the initial attempt to get the data failed, and it would periodically retry until a successful retrieval of the data occurred.  Implementing and testing this doesn't seem like the best use of my time at the moment given my other priorities, so I'm going to start with a simpler solution: I'll add a try/catch block that will log an error and null out the promise so that the next attempt to get the data - most likely due to a user loading the translation selection page - should cause an update.  The risk here is that if the initial update fails and then the update triggered by the user interaction fails, there would be no information with which to populate the translation selection page.  This is pretty unlikely to happen and, even if it does, the user would just see an odd page (no sims to choose for translation) and would have to try again later.

Here is the log entry that shows the restart when the problem started.  Note the error messages related to the initial population of the simData object:

```
Apr 25 22:43:09 phet-server.int.colorado.edu rosetta[62060]: Apr 25 2018 22:43:09 MDT - info: ---- rosetta starting up ----
Apr 25 22:43:09 phet-server.int.colorado.edu rosetta[62060]: Apr 25 2018 22:43:09 MDT - info: Node version: v8.9.0
Apr 25 22:43:09 phet-server.int.colorado.edu rosetta[62060]: Warning: connect.session() MemoryStore is not
Apr 25 22:43:09 phet-server.int.colorado.edu rosetta[62060]: designed for a production environment, as it will leak
Apr 25 22:43:09 phet-server.int.colorado.edu rosetta[62060]: memory, and will not scale past a single process.
Apr 25 22:43:09 phet-server.int.colorado.edu rosetta[62060]: Apr 25 2018 22:43:09 MDT - info: Listening on port 16372
Apr 25 22:43:09 phet-server.int.colorado.edu rosetta[62060]: Apr 25 2018 22:43:09 MDT - error: metadata retrieval failed, err = SyntaxError: Unexpected end of JSON input
Apr 25 22:43:09 phet-server.int.colorado.edu rosetta[62060]: Apr 25 2018 22:43:09 MDT - info: initial population of simData object failed, err = SyntaxError: Unexpected end of JSON input
```

Here are the messages that were occurring later when the code was trying to access `simData`, and as a result ended up trying to wait on an already rejected promise:

```
Apr 26 10:14:13 phet-server.int.colorado.edu rosetta[65482]: Apr 26 2018 10:14:13 MDT - info: a request for metadata is in progress, waiting on that promise
Apr 26 10:14:13 phet-server.int.colorado.edu rosetta[65482]: Apr 26 2018 10:14:13 MDT - error: unhandled rejection, error.message = Unexpected end of JSON input
```

...and here is the log entry that shows the restart and subsequent successful population of `simData` (done by @mattpen and mentioned in previous comments):

```
Apr 26 10:18:01 phet-server.int.colorado.edu rosetta[61856]: Apr 26 2018 10:18:01 MDT - info: ---- rosetta starting up ----
Apr 26 10:18:01 phet-server.int.colorado.edu rosetta[61856]: Apr 26 2018 10:18:01 MDT - info: Node version: v8.9.0
Apr 26 10:18:01 phet-server.int.colorado.edu rosetta[61856]: Warning: connect.session() MemoryStore is not
Apr 26 10:18:01 phet-server.int.colorado.edu rosetta[61856]: designed for a production environment, as it will leak
Apr 26 10:18:01 phet-server.int.colorado.edu rosetta[61856]: memory, and will not scale past a single process.
Apr 26 10:18:01 phet-server.int.colorado.edu rosetta[61856]: Apr 26 2018 10:18:01 MDT - info: Listening on port 16372
Apr 26 10:18:01 phet-server.int.colorado.edu rosetta[61856]: Apr 26 2018 10:18:01 MDT - info: initial population of simData object complete
```

**Comment by jbphet** [comment] 2018-04-27 18:29
@mattpen - I did a little more digging, and the reason that rosetta restarted was that someone tried to log in, rosetta tried to validate their credentials, and the JSON response that came back was bad.  I will add error handling for this, but here is what I'm seeing in the log:

```
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: Apr 25 2018 22:54:40 MDT - info: data received: <!DOCTYPE html>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: <html>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: <head>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: <title>503 Backend fetch failed</title>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: </head>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: <body>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: <h1>Error 503 Backend fetch failed</h1>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: <p>Backend fetch failed</p>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: <h3>Guru Meditation:</h3>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: <p>XID: 184709246</p>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: <hr>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: <p>Varnish cache server</p>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: </body>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: </html>
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: undefined:1
Apr 25 22:54:40 phet-server.int.colorado.edu rosetta[65380]: <!DOCTYPE html>
```

Does this give us any insight into what was happening when the restart occurred?

**Comment by mattpen** [comment] 2018-04-30 16:54
@jbphet - I believe that this error occurred during a server restart for a website redeploy.  Are there any changes needed on the website side?

**Comment by jbphet** [comment] 2018-05-01 13:51
@mattpen - I don't think any server side changes are required, I just wanted to understand what triggered the problem in the first place, and your explanation makes sense.  I think I have a workable solution in place, and I've tested it a bit, but it's difficult to have much confidence until it has run for a while. I'll keep the issue open for a month and set reminders to check it periodically and, if we see no problems of this nature during that time, I'll close.

**Comment by jbphet** [comment] 2018-05-07 22:40
It's only been about a week since the fix was implemented for this issue, but since we've received a number of translations (due to the publication of the Area Model sim suite) without any problems errors, I think it's safe to close this.

**Closed by jbphet** 2018-05-07 22:40 UTC
