### ISSUE TITLE
UX mockups

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#8] opened 2015-03-09 18:25 UTC
On 2/17/15, @ariel-phet and I met to do UX design. The end result was a PDF file of my notebook sketches. The intention was to flesh those out and share them with the design team.  In the past few design meetings, I've been feeling more urgency about this issue, since it's clear that we're not all entirely on the same page about the UX.

Assigning to @ariel-phet to move this forward.

**Comment by ariel-phet** [comment] 2015-04-04 19:04
I am finding it tough to carve out a time to do this...I will work with our graphic artist to move things forward

https://github.com/phetsims/tasks/issues/212

**Comment by ariel-phet** [comment] 2015-05-12 03:17
Closing this issue, since it is now being worked on by our graphic artist and a duplicate of the tasks issue

**Closed by ariel-phet** 2015-05-12 03:17 UTC
Labels: high priority
