### ISSUE TITLE
test simultaneous commits

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#93] opened 2015-09-30 19:31 UTC
While doing the code review, it occurred to me that we probably haven't tested the case where simultaneous commits occur to the strings repository.  The code looks like it should handle it, but it would be good to test it out to be sure.  I think we should test three cases:

+ simultaneously submit translations for two different simulations in different languages
+ simultaneously submit translations for the same simulation in different languages
+ simultaneously submit translations for the same simulation in the same language

The third case is unlikely to occur while we are working only with a single trusted translator per language, but it would still be good to know what happens.

**Comment by jbphet** [comment] 2015-09-30 19:31
Assigning to @ariel-phet so that he can give this to someone on the QA team.

**Comment by phet-steele** [comment] 2015-10-02 17:08
Testing the first scenario, two different sims + two different locales:

The first occurrence of weirdness happened here: https://github.com/phetsims/babel/commit/e05bc8465bde8bf0e0c917ac96dbb5c8778ada6f

This needs some explanation so you know what I did.

There are two different computers being used here, computer 1 and computer 2.
Computer 1 is translating molecule-shapes_kn
Computer 2 is translating molecules-and-light_iu (**pay attention to the locales for each computer!**)

I translated every string available in each sim (sim, shared, common, you name it!), computer 1 had its strings translated in numerical order from 1-78, and computer 2 was translated from 101-167. I did this not to remember each string's specific translation (there's way too many strings to memorize!), but just to know that any two digit number translation came from computer 1 and any three digit number came from computer 2.

So to reiterate the important parts:
Computer 1 is _kn and two digit translations
Computer 2 is _iu and three digit translations

The above commit is for joist-strings_kn.json (**_kn from computer 1!**), but you can clearly see the addition of some three digit numbers (**from computer 2!**). Computer 2 should have nothing to do with this file, it's translating a different language.

What I did:
1. Translated the sims as described above and submitted simultaneously. This went off without a hitch.
2. I went back to each sim and changed some string values in each. This was so that I could submit a second time. As to what I actually changed, I changed **ONLY** a couple sim strings in each, **NOT** any joist strings. (What I changed them to is most likely not important).
3. After simultaneously submitting from those changes, the above commit happened. You'd think it shouldn't since I never touched any joist strings during the second submissions.

You can look at the timestamps in each addition as well and see they are shown to have happened before the deletions, which doesn't make any logical sense. The actual joist-strings_kn.json
file shows a history of the string value for "adaptedFrom" going from blank to 133 then to 39. This is completely false, I only ever submitted joist strings once and should only see this sting going from blank directly to 39. Remember that _kn should only have two digit numbers in its commits, too.
```js
{
  "adaptedFrom": {
    "value": "39",
    "history": [
      {
        "userId": 130708,
        "timestamp": 1443801199247,
        "oldValue": "",
        "newValue": "133",
        "explanation": null
      },
      {
        "userId": 195724,
        "timestamp": 1443802119461,
        "oldValue": "133",
        "newValue": "39",
        "explanation": null
      }
    ]
  },
```

I hope this all makes sense to you @aaronsamuel137!

**Comment by phet-steele** [comment] 2015-10-02 17:30
Successfully reproduced

**Comment by phet-steele** [comment] 2015-10-02 18:04
For scenario two, one sim + two different locales:

Same thing happened as in the previous scenario, with an additional effect. In the first scenario, computer 2 translations appeared in the computer 1 joist file. This happened in this scenario as the first commit, as well as computer 1 translations appearing in the computer 2 joist file as a second commit. However, this second commit is not replacing lines like the first commit and first scenario do: https://github.com/phetsims/babel/commit/7572e464502a8fb77582e4eaf9fac155695d67e1

So what seems to be happening is that the common code strings from one locale are affecting the common code strings from another locale. So far sim specific strings have been unaffected.

**Comment by phet-steele** [comment] 2015-10-02 18:27
For scenario three, one sim + one locale:

Working as expected, the second submission (second by a few milliseconds) replaces string values from the first submission. The history of these events are also successfully recorded in the commit.

**Comment by jbphet** [comment] 2015-10-05 17:31
It looks like @phet-steele has found some potential issues in the course of this testing.  Assigning to @aaronsamuel137 to investigate.

**Comment by aaronsamuel137** [comment] 2015-10-05 19:12
Ah looks like there was a bug here where histories were looked up by repo name, but it didn't account for locale. I think I've fixed it.

Can you try this again @phet-steele and see if it works?

**Comment by aaronsamuel137** [comment] 2015-10-16 15:17
@ariel-phet, can we make testing this a top priority for @phet-steele? It would be great to verify this is fixed now that molarity is translatable on figaro.

**Comment by aaronsamuel137** [comment] 2015-10-16 15:20
@phet-steele, if you are going to test this let me know, since I'll need to make sure the right version of rosetta is running for this test.

**Comment by ariel-phet** [comment] 2015-10-16 16:25
@phet-steele - please test this today if at ALL possible.

**Comment by aaronsamuel137** [comment] 2015-10-16 17:02
Rosetta is ready to go on simian for testing. We should wait until this is done before unleashing the translators on molarity on figaro.

**Comment by phet-steele** [comment] 2015-10-21 17:31
@aaronsamuel137 all the testing I've done with this has been with M&L and Molecule Shapes without any built versions. Would it be worth it for me to test Molarity and Hooke's Law  with built versions now that they're up? Or would you not expect anything different?

**Comment by aaronsamuel137** [comment] 2015-10-21 17:38
You could do one or two tests here just to make sure it's all still good.

**Comment by aaronsamuel137** [comment] 2015-10-29 18:10
Can we close this @phet-steele? Any remaining issues you are aware of here?

**Comment by phet-steele** [comment] 2015-11-13 16:20
Yes, this can be closed.

**Closed by phet-steele** 2015-11-13 16:20 UTC
Labels: code-review, high priority
