### ISSUE TITLE
limit translators to a set of locales

### ISSUE THREAD

**Issue by jbphet** [phetsims/rosetta#109] opened 2015-12-10 18:08 UTC
During the 12/10/2015 status meeting @oliver-phet mentioned that trusted translators are able to submit translations to any locale.  This probably isn't the best idea, and we should make it so that translators have a limited set of locales that they are allowed to translate.  This list would be set up manually by Oliver based on the user's request.

This feature would involve changes on the web site too, such as adding a page where a user could request translation privileges and specify the desired locales.

**Comment by oliver-phet** [comment] 2022-07-28 22:23
Closing, duplicate of #301, and notes are being kept in that issue.

**Closed by oliver-phet** 2022-07-28 22:23 UTC
