### ISSUE TITLE
branch: test-fixes-for-overwrite-issue

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#181] opened 2018-02-08 18:05 UTC
Identified by `print-branches.sh`. @jbphet please describe.

**Comment by jbphet** [comment] 2018-02-09 19:51
I looked through the commits on this branch, and I made them, but I can't recall what it was all about.  The commits aren't referenced to a GitHub issue, which is unfortunate (my bad).  At the time of this writing there are 27 commits on this branch that never made it into master, but most of them look like debug logging and such.  It has been about 2 years since the last commit, so I think it is unlikely that I or anyone else will need to go back to this.

I'm going to leave this branch around for a while in case it comes to me what this was all about, but if it hasn't been used by, say June 2018, this branch should just be deleted.

**Comment by jbphet** [comment] 2018-02-21 19:02
I have put a reminder on my calendar for this.

**Comment by jbphet** [comment] 2018-04-23 19:32
This is a duplicate of #129, and there is information in that issue about why the branch was needed.  Closing.

**Closed by jbphet** 2018-04-23 19:32 UTC
Labels: priority:5-deferred
