### ISSUE TITLE
Augment PUSH FAILED message with helpful information

### ISSUE THREAD

**Issue by samreid** [phetsims/rosetta#110] opened 2015-12-18 14:25 UTC
Today I received this PUSH FAILED email:

> Error: Repo updateContents error

> Error: Repo updateContents error. Error committing to file scenery-phet/scenery-phet-strings_da.json

> [{"stringKey":"FaceWithPointsNode.pattern_0sign_1points","stringValue":"{0}{1}"}]

It would be very helpful if we augmented these emails with a link to something like "common problems and how to resolve them".

@jbphet I'm not sure who should work on this, can you help decide?

**Comment by jbphet** [comment] 2015-12-18 16:37
This is essentially a duplicate of https://github.com/phetsims/rosetta/issues/105.  This issue is known, the error message is spurious, and as discussed is yesterday's developer meeting, will be addressed in about a month.  We can't really had helpful information to a message that shouldn't be sent in the first place.

I propose temporarily updating the list of recipients for these messages to include only @phetsims/matt-p, @jonathanolson, and me so that others aren't distracted by them, and closing this issue and fully addressing the problem when we work on #105.

**Comment by samreid** [comment] 2015-12-18 17:07
Sounds good, how does one update the list of recipients?

**Comment by jbphet** [comment] 2015-12-18 18:59
@samreid  - the list of recipients is maintained in the preferences file.  I can provide details via voice call, would rather not post them here since it's a public repo.

**Comment by jbphet** [comment] 2015-12-18 18:59
List of email recipients updated, closing.

**Closed by jbphet** 2015-12-18 18:59 UTC
