### ISSUE TITLE
Investigate cause of Rosetta string pattern validation failures

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/rosetta#329] opened 2022-08-31 02:14 UTC
molecule-polarity-strings_da.json has a problem with pattern strings.  The placeholder names have been changed.

This English string:

```
  "pattern.dipoleDirection": {
    "value": "{{from}} → {{to}}"
  },
```

... is used to fill in these radio button labels, which appear in Preferences:

<img width="108" alt="screenshot_1846" src="https://user-images.githubusercontent.com/3046552/187577224-2f73fd08-3212-4f16-8285-5add746d73ca.png">

The current 'da' translation is:

```
 "pattern.dipoleDirection": {
    "value": "{{fra}} → {{til}}",
```

This makes it impossible to fill in the pattern correctly, and it shows up in the sim UI like this:

<img width="126" alt="screenshot_1845" src="https://user-images.githubusercontent.com/3046552/187576920-0d5462fe-6b0c-4de3-bbab-ef220bee68ab.png">

The problem is that the translator has translated the placeholders, which are not supposed to be changed, and that makes it impossible for the sim to fill in the blanks. Rosetta is supposed to prevent this (@jbphet FYI). Is Rosetta working correctly? Do other translations have this problem?  Should the 'da' trusted translator be notified.

Assigning to @kathy-phet to decide on next steps.

**Comment by zepumph** [comment] 2022-12-16 01:26
RE: https://github.com/phetsims/rosetta/issues/329#issuecomment-1354048256, 

@oliver-phet, can you please confirm that the Rosetta UI will not allow you to submit translations in which you changed the template var?

**Comment by oliver-phet** [comment] 2022-12-16 02:01
> RE: [#329 (comment)](https://github.com/phetsims/rosetta/issues/329#issuecomment-1354048256),
> 
> @oliver-phet, can you please confirm that the Rosetta UI will not allow you to submit translations in which you changed the template var?

Rosetta (1.0) does not allow a translator to submit a translation with a template var changed.
<img width="926" alt="image" src="https://user-images.githubusercontent.com/5090275/208004582-6b58c44e-e593-49b4-8ce9-a0b5187fac76.png">

Trying to submit anyway:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/5090275/208004625-2f86fa8a-1365-44e5-bf23-2ba9948b45e9.png">

**Comment by liammulh** [comment] 2022-12-16 02:49
Not an issue in Rosetta 2.0 either:

<img width="932" alt="Screen Shot 2022-12-15 at 7 48 30 PM" src="https://user-images.githubusercontent.com/60749003/208010699-66a4d2f7-e77f-4b87-a01a-a749b6468c57.png">

(Buttons are disabled if there's a form error.)

**Comment by oliver-phet** [comment] 2022-12-16 18:50
As I'm looking to correct the pattern translations in https://github.com/phetsims/babel/issues/18

I'm concerned seeing something like this:
number-play-strings_ht.json@wordLanguage:
english vars: [ '{{language}}' ]
translated vars: [ '{{langue}}' ]

As far as I can tell, [Number play was translated into Haitian](https://github.com/phetsims/babel/blob/master/number-play/number-play-strings_ht.json) on Wed Nov 30 2022 22:14:54. So it would seem the Rosetta validation isn't _always_ working. I haven't personally seen a failure case, but this example at least provides a need for more validation investigation and testing by @jbphet & @liammulh.

**Comment by oliver-phet** [comment] 2022-12-16 23:34
@liammulh can you verify if Rosetta 2.0 is using the same regex validation that 1.0 used? (If so, we might just want to fix this in 2.0)

**Comment by jbphet** [comment] 2022-12-16 23:40
Here is one thought as to why this is happening in Rosetta 1: Perhaps the users are disabling JavaScript.  I stuck a screenshot below of how this can be done in Chrome.  Since the validation is all done in the client code for Rosetta 1, disabling JavaScript might be a way to cause this sort of outcome (i.e. incorrectly translated patterns).

![image](https://user-images.githubusercontent.com/3082831/208208383-6cf8568e-6ded-4e3b-a271-69c7f254444b.png)

**Comment by liammulh** [comment] 2022-12-16 23:50
Rosetta 2 uses the same regex.

**Comment by jbphet** [comment] 2022-12-16 23:51
@oliver-phet - Can you test if disabling JS make this possible in Rosetta 1?

**Comment by liammulh** [comment] 2022-12-16 23:51
You won't even be able to use the translation utility if you disable JS for Rosetta 2, so if that's the cause, then Rosetta 2 is the solution.

**Comment by pixelzoom** [comment] 2022-12-17 00:08
If people are disabling JS, then they're not running the sim that they translated, and therefore not testing their translation. Radical idea: Perhaps Rosetta show require the user to disable the Submit button until the Test button has been pressed at least once?

**Comment by pixelzoom** [comment] 2022-12-17 00:09
If people are disabling JS, then they're not running the sim that they translated, and therefore not testing their translation. Radical idea: Perhaps Rosetta should require the user to disable the Submit button until the Test button has been pressed at least once? Or if not disable the Submit button, pop up a dialog that says something like "You cannot Submit until you Test."

**Comment by oliver-phet** [comment] 2023-01-02 18:12
> @oliver-phet - Can you test if disabling JS make this possible in Rosetta 1?

I disabled Javascript in Safari and did a few tests. It seems unlikely this was how these translations bypassed validation:
(Tested with Acid-Base Solutions, Abkhazian _ab)_

1. With Javascript disabled, I couldn't even click 'Go' after selecting a Sim and Locale.
2. I enabled JS, selected a sim and locale, then disabled JS. This allowed me to enter gibberish in a pattern, but similarly, I couldn't click Save or Test. I _could_ click Submit and I got the success screen, but the build seemed to fail ([no babel file](https://github.com/phetsims/babel/tree/master/acid-base-solutions), [or translation](https://phet.colorado.edu/en/simulations/filter?locale=ab) was created)

BUILD ERROR email:
```
Build failure: Error: Build aborted, Error: grunt build-for-server --brand=phet --locales=ab --allHTML in ../acid-base-solutions failed with exit code 3
stdout:
[4mRunning "eslint:allFiles" (eslint) task[24m


[4mRunning "clean" task[24m

[4mRunning "requirejs:build" (requirejs) task[24m
[32m>> [39mRequireJS optimizer finished

[4m/data/share/phet/build-server/acid-base-solutions/build/acid-base-solutions.min.js[24m
Uncompressed size: [32m2108861[39m bytes.
Compressed size: [32m367002[39m bytes gzipped. ([32m994815[39m bytes minified)

[4mRunning "after-requirejs-build" task[24m
[31mFatal error: Cannot read properties of undefined (reading 'ACID_BASE_SOLUTIONS/acid-base-solutions.title')[39m

stderr:
(node:1229855) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
 Sim = acid-base-solutions Version = 1.2.29 Brands = phet Locales = ab Shas = {"comment":"# acid-base-solutions 1.2.29 Sun Dec 25 2022 07:28:16 GMT-0700 (Mountain Standard Time)","acid-base-solutions":{"sha":"30acd66d97d98019f026c1ac5a1e72f0e80142ef","branch":"HEAD"},"assert":{"sha":"11bc6a6d0344ba1a8b95982bad3552bffbdfdfd6","branch":"HEAD"},"axon":{"sha":"ec0f621f9e7400cdb38d3489ee41e43e9c284202","branch":"HEAD"},"brand":{"sha":"0d3f9ddebfb021dfcfb2cc0d90579844558a4f2a","branch":"HEAD"},"chipper":{"sha":"0bbc5f370fbe11dd91f9a50e26ef9944ff6e140b","branch":"HEAD"},"dot":{"sha":"b9e3c1e07271b8b4fee91fca360f51563fe479cb","branch":"HEAD"},"joist":{"sha":"1d85b97df14baaad5b3622745e58d043813be654","branch":"HEAD"},"kite":{"sha":"7f2df7e9ec52ed32d8c0fe0c1fe6bfa8c043c510","branch":"HEAD"},"phet-core":{"sha":"15b76d2d658339ee51868f22805807f34253994e","branch":"HEAD"},"phetcommon":{"sha":"cc3dbc2d60e99e41edf57a3a1eed5c97e61e4294","branch":"HEAD"},"phetmarks":{"sha":"fe43b1cbadd83e554e5de715e8bfd39ec5566087","branch":"HEAD"},"scenery":{"sha":"7bf76436ac90dc04e6df419f3a76ef9800e6e7e1","branch":"HEAD"},"scenery-phet":{"sha":"be0e4c5fbc59e632d91cc7edfd605ffcebecded2","branch":"HEAD"},"sherpa":{"sha":"f3cf6285fe2e85ce9b8998db4f3361837fc8d9ce","branch":"HEAD"},"sun":{"sha":"f678dd20763b18182a16b7725fecc45d92bdf8fd","branch":"HEAD"},"tandem":{"sha":"210ece84c1dfdce1aedb77e451cd0ddc376db313","branch":"HEAD"}}
```

**Comment by oliver-phet** [comment] 2023-01-02 18:14
If the build failure was due to another cause, then it is _possible_ to bypass validation by disabling JS (but only after selecting a Sim/Locale).

**Comment by kathy-phet** [comment] 2023-01-02 20:10
@jbphet - Do you see these build errors? Can you interpret for @oliver-phet?

**Comment by jbphet** [comment] 2023-01-04 21:55
I modified @zepumph's script to not included zero-length strings, since these values are valid (the string-handling code will fall back to the English value in this case) and checked the script into `rosetta/scripts/js`.  This should make it a little easier to interpret the results and to re-run when needed.

The results are shown below.  According to these results, there are 32 patterns that need to be fixed up.

<details>

```
Analyzing translations for mismatched patterns...
---------------
Pattern mismatch detected:
  translatedFileName = circuit-construction-kit-common-strings_nb.json
  stringKey = resistanceOhmsSymbol
  englishStringValue = {{resistance}} Ω
  translated value = {resistance}} Ω
---------------
Pattern mismatch detected:
  translatedFileName = expression-exchange-strings_ko.json
  stringKey = numberCentsPattern
  englishStringValue = {{number}} cents
  translated value = {{수)}} 센트
---------------
Pattern mismatch detected:
  translatedFileName = expression-exchange-strings_zh_CN.json
  stringKey = numberCentsPattern
  englishStringValue = {{number}} cents
  translated value = {{数字}} 分
---------------
Pattern mismatch detected:
  translatedFileName = expression-exchange-strings_ko.json
  stringKey = levelNumberPattern
  englishStringValue = Level {{levelNumber}}
  translated value = 수준((짝수}}
---------------
Pattern mismatch detected:
  translatedFileName = expression-exchange-strings_zh_CN.json
  stringKey = levelNumberPattern
  englishStringValue = Level {{levelNumber}}
  translated value = 水平 {{水平数字}}
---------------
Pattern mismatch detected:
  translatedFileName = gene-expression-essentials-strings_es_ES.json
  stringKey = gene
  englishStringValue = Gene {{geneID}}
  translated value = Gen
---------------
Pattern mismatch detected:
  translatedFileName = gene-expression-essentials-strings_fa.json
  stringKey = gene
  englishStringValue = Gene {{geneID}}
  translated value = ژن
---------------
Pattern mismatch detected:
  translatedFileName = gene-expression-essentials-strings_ja.json
  stringKey = gene
  englishStringValue = Gene {{geneID}}
  translated value = 遺伝子
---------------
Pattern mismatch detected:
  translatedFileName = gene-expression-essentials-strings_mk.json
  stringKey = gene
  englishStringValue = Gene {{geneID}}
  translated value = Ген
---------------
Pattern mismatch detected:
  translatedFileName = gene-expression-essentials-strings_ta.json
  stringKey = gene
  englishStringValue = Gene {{geneID}}
  translated value = மரபணு
---------------
Pattern mismatch detected:
  translatedFileName = molecule-polarity-strings_fa.json
  stringKey = pattern.atomName
  englishStringValue = Atom {{name}}
  translated value = اتم
---------------
Pattern mismatch detected:
  translatedFileName = molecule-polarity-strings_ko.json
  stringKey = pattern.atomName
  englishStringValue = Atom {{name}}
  translated value = 원자 {{이름}}
---------------
Pattern mismatch detected:
  translatedFileName = molecule-polarity-strings_zh_CN.json
  stringKey = pattern.atomName
  englishStringValue = Atom {{name}}
  translated value = 原子{{名字}}
---------------
Pattern mismatch detected:
  translatedFileName = molecule-polarity-strings_ko.json
  stringKey = pattern.symbolName
  englishStringValue = {{symbol}} ({{name}})
  translated value = {{기호}} ({{이름}})
---------------
Pattern mismatch detected:
  translatedFileName = molecule-polarity-strings_zh_CN.json
  stringKey = pattern.symbolName
  englishStringValue = {{symbol}} ({{name}})
  translated value = {{标志}} ({{名字}})
---------------
Pattern mismatch detected:
  translatedFileName = molecule-polarity-strings_bs.json
  stringKey = pattern.dipoleDirection
  englishStringValue = {{from}} → {{to}}
  translated value = {{od}} → {{do}}
---------------
Pattern mismatch detected:
  translatedFileName = molecule-polarity-strings_da.json
  stringKey = pattern.dipoleDirection
  englishStringValue = {{from}} → {{to}}
  translated value = {{fra}} → {{til}}
---------------
Pattern mismatch detected:
  translatedFileName = molecule-polarity-strings_ko.json
  stringKey = pattern.dipoleDirection
  englishStringValue = {{from}} → {{to}}
  translated value = {{에서}} → {{로}}
---------------
Pattern mismatch detected:
  translatedFileName = molecule-polarity-strings_vi.json
  stringKey = pattern.dipoleDirection
  englishStringValue = {{from}} → {{to}}
  translated value = {{từ}} → {{đến}}
---------------
Pattern mismatch detected:
  translatedFileName = molecule-polarity-strings_zh_CN.json
  stringKey = pattern.dipoleDirection
  englishStringValue = {{from}} → {{to}}
  translated value = {{从}} → {{到}}
---------------
Pattern mismatch detected:
  translatedFileName = number-play-strings_ht.json
  stringKey = wordLanguage
  englishStringValue = Word ({{language}})
  translated value = Mo ({{langue}})
---------------
Pattern mismatch detected:
  translatedFileName = pendulum-lab-strings_nb.json
  stringKey = gravitationalAccelerationPattern
  englishStringValue = {{gravity}} m/s<sup>2</sup>
  translated value = {{gravitasjon}} m/s<sup>2</sup>
---------------
Pattern mismatch detected:
  translatedFileName = pendulum-lab-strings_nb.json
  stringKey = degreesPattern
  englishStringValue = {{degrees}}°
  translated value = {{grader}}°
---------------
Pattern mismatch detected:
  translatedFileName = pendulum-lab-strings_nb.json
  stringKey = secondsPattern
  englishStringValue = {{seconds}} s
  translated value = {{sekunder}} s
---------------
Pattern mismatch detected:
  translatedFileName = proportion-playground-strings_eu.json
  stringKey = pricePattern
  englishStringValue = ${{price}}
  translated value = ${{prezioa}}
---------------
Pattern mismatch detected:
  translatedFileName = proportion-playground-strings_ko.json
  stringKey = pricePattern
  englishStringValue = ${{price}}
  translated value = ${{가격}}
---------------
Pattern mismatch detected:
  translatedFileName = proportion-playground-strings_vi.json
  stringKey = pricePattern
  englishStringValue = ${{price}}
  translated value = ${{giá}}
---------------
Pattern mismatch detected:
  translatedFileName = proportion-playground-strings_zh_CN.json
  stringKey = pricePattern
  englishStringValue = ${{price}}
  translated value = ${{单价}}
---------------
Pattern mismatch detected:
  translatedFileName = scenery-phet-strings_ht.json
  stringKey = keyboardHelpDialog.grabOrReleaseHeadingPattern
  englishStringValue = Grab or Release {{thing}}
  translated value = Pran oubyen Lage {{chose}}
---------------
Pattern mismatch detected:
  translatedFileName = scenery-phet-strings_ht.json
  stringKey = keyboardHelpDialog.grabOrReleaseLabelPattern
  englishStringValue = Grab or release {{thing}}
  translated value = Pran oubyen lage {{chose}}
---------------
Pattern mismatch detected:
  translatedFileName = scenery-phet-strings_ht.json
  stringKey = measuringTapeReadoutPattern
  englishStringValue = {{distance}} {{units}}
  translated value = {{distance}} {{unités}}
---------------
Pattern mismatch detected:
  translatedFileName = scenery-phet-strings_tg.json
  stringKey = measuringTapeReadoutPattern
  englishStringValue = {{distance}} {{units}}
  translated value = {{масофа}} {{адад}}

Analysis complete, number of mismatched patterns found = 32
```

</details>

It's still a mystery to me how these are getting through, but it sounds like the plan is to just live with it for now since Rosetta 2.0 will soon replace Rosetta 1.  I'll put a reminder on my calendar to check weekly for new broken patterns in the mean time.

**Comment by oliver-phet** [comment] 2023-01-04 23:57
Most sim-specific babel files have been fixed and (uncredited) builds have been triggered.

Waiting for more input on expression-exchange-strings. For some reason the babel files for that sim are missing string history and I want to ensure nothing will break if I edit and build those.

There were 2 common repos in @jbphet 's script output:

- circuit-construction-kit-common-strings
- scenery-phet-strings

According to @jbphet "You can't rebuild common ones, you have rebuild all the sims that use it. The unfortunate answer is that pretty much EVERY sim using scenery-phet, but they don't necessarily use the pattern in question.  I don't want you to have to rebuild every sim for a given locale, so assign the issue to me and I'll make a list of the sims that use the patterns in the common-code repos, and thus need to be rebuilt."

So he is going to take care of the scenery-phet cases.

**Comment by oliver-phet** [comment] 2023-01-05 00:37
@jbphet I tried fixing expression-exchange-strings and received the following error:

> Translation Utility Error
> 
> Invalid user ID.
> 
> If this problem has occurred multiple times and is preventing you from working on translations, please contact phethelp@colorado.edu, and include all information on this page.
> 
> Timestamp: 1672878921482
> 
> Details: request.params.userId did not match a user ID in the string file fetched from Babel.

All 5 of the locales that miss the pattern validation don't have history (they were ported from the Java translation), so I suspect I'd receive the same error for all of these.

**Comment by jbphet** [comment] 2023-01-06 19:21
I have added a reminder to my calendar to check for new bad pattern translations every week.  I'll do this for a while, including after Rosetta 2.0 is live, and if we don't see any problems after a few months, I'll close this issue.

**Comment by liammulh** [comment] 2023-01-07 00:33
I fixed the issue @oliver-phet described in https://github.com/phetsims/rosetta/issues/329#issuecomment-1371588737 in https://github.com/phetsims/rosetta/commit/613efdcfa5ad26fce9c3226164fe144b67471f1f in Rosetta 2.0. I think @jbphet has a patch ready for Rosetta 1.0.

**Comment by jbphet** [comment] 2023-01-11 23:32
@oliver-phet - @liammulh and I have fixed the issue that was preventing submission of string files that contained no user IDs that you ran into in https://github.com/phetsims/rosetta/issues/329#issuecomment-1371588737.  Can you please try again to trigger rebuilds of those translations?

**Comment by oliver-phet** [comment] 2023-01-12 00:01
@jbphet Success! Those missing gene-expression-essentials-strings fixes have been committed and built!

I did the best I could crediting the correct translator (searching legacy build credits) but 2 legacy translators no longer have PhET accounts, so I just credited a more recent translator in the same locale.

**Comment by jbphet** [comment] 2023-01-19 19:43
Below is the list of sims that need to be rebuilt once all of the patterns have been corrected.  I created this by looking at the list of common code strings in the "details" section of [this comment](https://github.com/phetsims/rosetta/issues/329#issuecomment-1371475067) above, then following the string to its usages in classes, and the use of those classes in sims.  It was a very manual process, and may not have identified everything, but it should certainly cover most.

As a reminder, the patterns need to be fixed in babel before these sims are republished.  I just ran the analysis script and there are still 5 patterns to be fixed (@oliver-phet - please let me know if that list would be useful).

- For locale `ht` (Haitian)
  - friction
  - faradays-law
  - gravity-force-lab
  - charges-and-fields
  - energy-skate-park
  - gravity-and-orbits
  - my-solar-system
  - projectile-motion
  - wave-interference
- For locale `tg` (Tajik)
  - charges-and-fields
  - my-solar-system
  - wave-interference

For reference, here is a screenshot of how this issue manifests in the currently live `ht` translation of energy-skate-park:

![image](https://user-images.githubusercontent.com/3082831/213540143-e3b4b694-4e81-4463-b83c-6550a159584a.png)

**Comment by oliver-phet** [comment] 2023-01-20 19:47
@jbphet I've committed all the string fixes and attempted to build the sims you listed. Here's the result - mostly failed due to invalid user id. If there's something else I can do to resolve, let me know. Back to you.


repo | locale | result
-- | -- | --
friction | ht | invalid user ID
faradays-law | ht | invalid user ID
gravity-force-lab | ht | invalid user ID
charges-and-fields | ht | invalid user ID
energy-skate-park | ht | invalid user ID
gravity-and-orbits | ht | invalid user ID
my-solar-system | ht | unable to get string file from babel
projectile-motion | ht | invalid user ID
wave-interference | ht | invalid user ID
  |   |  
charges-and-fields | tg | Triggered Build Successfully
my-solar-system | tg | Triggered Build Successfully
wave-interference | tg | invalid user ID

**Comment by oliver-phet** [comment] 2023-01-20 23:04
Alright, all of the fixes for the invalid user id's have been made. Closing!

**Closed by oliver-phet** 2023-01-20 23:04 UTC
Labels: type:bug, type:i18n, status:ready-for-review

**Comment by jbphet** [comment] 2023-06-16 22:42
I just checked and verified that this problem is no longer occurring in submitted string files.

**Comment by jbphet** [comment] 2023-07-14 18:14
I just did one last check using the `find-bad-pattern-translations.js`, and am not seeing any bad patterns.  I'm removing the reminder from the calendar and won't check again unless something leads me to believe that it's become a problem again.
