### ISSUE TITLE
Use OAuth or Tokens for Rosetta authentication

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/rosetta#245] opened 2020-11-17 18:13 UTC
It sounds like @jbphet is going to transition rosetta from using basic authentication to OAuth or Tokens. This is currently blocking HTML5 sim translation.

Also assigning @ariel-phet for prioritization. 

From Slack:

> Bad credentials. The API can’t be accessed using username/password authentication. Please create a personal access token to access this endpoint: http://github.com/settings/tokens

> Matt Pennington No, those are probably not related.  At first glance, it looks to me like something in rosetta is using a github API with basic authentication and it should be using OAuth or tokens
> 11:42 AM
> @jbphet are we still using basic authentication in rosetta anywhere?
> 11:42 AM
> (for github access)
> 11:44 AM
> John Blanco:house_with_garden: It's entirely possible.  Has GitHub disabled basic authentication?
> 12:08 PM
> Matt Pennington They've been threatening to disable it for several months
> 12:09 PM
> https://developer.github.com/changes/2020-02-14-deprecating-password-auth/
> 12:09 PM
> It looks like it was shut down permanently on 11/13
> 12:10 PM
> https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line  Good news is its is usually pretty easy to switch to personal access tokens.  This is what we're using for the scripts for issue labels.
> 12:13 PM
> John Blanco:house_with_garden: Okay.  I don't have time to fix it right now, so I'll set it up to show the "down for maintenance" screen and I'll get to it when I can.
> 12:19 PM
> John Blanco:house_with_garden: Okay, I've put it into the "offline" state, will get to sometime.

**Comment by ariel-phet** [comment] 2020-11-17 21:37
I think given the importance of translations to our project, fixing should be high priority (especially these days with our translation within apps, as well as the goals of Yidan prize). @jbphet you have my permission to let this fix supersede non-a11y priorities.

**Comment by muedli** [comment] 2020-11-19 00:10
@oliver-phet, John and I think we've fixed it. Could please let the translators know that we think we've fixed it? We'll keep an eye on it.

**Comment by muedli** [comment] 2020-11-19 00:12
Note to Self: We've fixed this on a branch. We'd like to get Rosetta back to master ASAP. We're leaving it assigned to myself and John to make sure that happens.

**Comment by oliver-phet** [comment] 2020-11-19 19:05
Translators notified, it looks like we received some new translations this morning so it appears to be working.

**Comment by jbphet** [comment] 2020-11-20 16:48
I also check the logs and saw several successfully submitted translations.

**Comment by jbphet** [comment] 2020-11-20 19:40
I'm going to remove the "priority:high" label, since the issue is mostly resolved and we are now just working to get back on master for the live versions.

**Comment by jbphet** [comment] 2020-12-10 23:09
@muedli and I worked together to get the current live version onto master.  I'll watch for a few days and make sure that translations are successfully coming in and, if so, we can close.

**Comment by muedli** [comment] 2021-01-28 22:38
We've set up PAT and we haven't seen any issues. Closing.

**Closed by muedli** 2021-01-28 22:38 UTC
Labels: type:i18n
